# Generated by Django 5.0.1 on 2024-05-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0005_profile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
