# Generated by Django 5.0.1 on 2024-05-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0006_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='more_info',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
