# Generated by Django 5.0.1 on 2024-06-01 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0012_attribute_cartitem_updated_at_category_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wsite.category'),
        ),
    ]
