# Generated by Django 5.0.1 on 2024-06-06 07:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0014_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='WishlistItem',
        ),
    ]
