# Generated by Django 5.0.1 on 2024-06-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0016_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
