# Generated by Django 5.0.1 on 2024-06-06 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsite', '0017_productrating_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
    ]
